version: '2'
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    build: ./docker/postgres
    ports:
        - "5432:5432"
#  image: tennis-prediction/postgres
